# Generated by Django 3.2.18 on 2023-03-24 12:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_ref', models.CharField(editable=False, max_length=50)),
                ('number_of_guests', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Number of guests')),
                ('booking_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('booked_on', models.DateTimeField(auto_now_add=True)),
                ('booked_by', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cruises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Cruise Name')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('duration', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(199)], verbose_name='Cruise Duration')),
                ('start_date', models.DateField(verbose_name='Cruise Start Date')),
                ('end_date', models.DateField(verbose_name='Cruise End Date')),
                ('description', models.TextField(max_length=2000, verbose_name='Cruise Description')),
                ('results_image', models.ImageField(upload_to='', verbose_name='Results Image')),
                ('listing_image', models.ImageField(upload_to='', verbose_name='Listing Image')),
                ('map_image', models.ImageField(upload_to='', verbose_name='Map Image')),
                ('bookable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Destination Name')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('continent', models.CharField(choices=[('Antarctica', 'Antarctica'), ('Africa', 'Africa'), ('Asia', 'Asia'), ('Europe', 'Europe'), ('North America', 'North America'), ('South America', 'South America'), ('Oceania', 'Oceania')], max_length=20)),
                ('description', models.TextField(max_length=700, verbose_name='Destination Description')),
                ('image', models.ImageField(upload_to='', verbose_name='Destination Image')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Destination Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Destination Longitude')),
            ],
        ),
        migrations.CreateModel(
            name='Ships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('total_suites', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2024)], verbose_name='Total number of suites on ship')),
                ('info_page', models.URLField(max_length=120, verbose_name='URL to information page')),
                ('ship_image', models.ImageField(upload_to='', verbose_name='Ship Image')),
            ],
        ),
        migrations.CreateModel(
            name='SuiteCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Suite Category Name')),
                ('description', models.TextField(max_length=350, verbose_name='Suite Category Description')),
                ('sleeps', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(4)], verbose_name='Category sleeps')),
                ('size', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(19), django.core.validators.MaxValueValidator(200)], verbose_name='Size of suite sq m')),
                ('suite_image', models.ImageField(upload_to='', verbose_name='Suite Image')),
                ('suite_layout_image', models.ImageField(upload_to='', verbose_name='Ship Layout Image')),
                ('suite_feature_list', models.CharField(blank=True, default='', max_length=3000, verbose_name='Suite Feature List')),
            ],
        ),
        migrations.CreateModel(
            name='Suites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suite_num_name', models.CharField(max_length=30, verbose_name='Suite Name/Number')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suite', to='cruises.suitecategories')),
                ('ship', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suite', to='cruises.ships')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Tag Name')),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_ref', models.CharField(editable=False, max_length=30, verbose_name='Ticket reference')),
                ('booked', models.BooleanField(default=False, verbose_name='Has ticket been booked?')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('cruise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket', to='cruises.cruises')),
                ('ship', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket', to='cruises.ships')),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket', to='cruises.suites')),
            ],
        ),
        migrations.CreateModel(
            name='Movements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(editable=False)),
                ('type', models.CharField(choices=[('D', 'Destination'), ('SD', 'Sea Day'), ('SC', 'Scenic Cruising')], max_length=2)),
                ('order', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)])),
                ('description', models.CharField(blank=True, default=None, max_length=120, null=True, verbose_name='Movement Description')),
                ('cruise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movement', to='cruises.cruises')),
                ('destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement', to='cruises.destination')),
                ('ship', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement', to='cruises.ships')),
            ],
        ),
        migrations.CreateModel(
            name='Guests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=9, verbose_name='Title')),
                ('first_name', models.CharField(max_length=25, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=25, verbose_name='Last Name')),
                ('dob', models.DateField(max_length=25, verbose_name='Date of Birth')),
                ('nationality', django_countries.fields.CountryField(max_length=2)),
                ('passport_number', models.CharField(max_length=20, verbose_name='Passport Number')),
                ('passport_expiry', models.DateField(verbose_name='Passport Expiry Date')),
                ('address_line_1', models.CharField(max_length=50, verbose_name='Address Line 1')),
                ('address_line_2', models.CharField(blank=True, max_length=50, verbose_name='Address Line 2')),
                ('town_city', models.CharField(max_length=50, verbose_name='Town/City')),
                ('state_county', models.CharField(blank=True, max_length=50, verbose_name='State/County')),
                ('zip_postcode', models.CharField(max_length=12, verbose_name='Zip/Post Code')),
                ('country_residence', django_countries.fields.CountryField(max_length=2)),
                ('email', models.EmailField(max_length=70, verbose_name='Email Address')),
                ('telephone', models.CharField(max_length=20, verbose_name='Telephone')),
                ('dietary_requirements', models.CharField(blank=True, max_length=200, verbose_name='Dietary Requirements')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest', to='cruises.bookings')),
            ],
        ),
        migrations.CreateModel(
            name='Fares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('special_offer', models.BooleanField(default=False)),
                ('offer_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('cruise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fares', to='cruises.cruises')),
                ('suite_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fares', to='cruises.suitecategories')),
            ],
        ),
        migrations.AddField(
            model_name='cruises',
            name='ship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cruises', to='cruises.ships'),
        ),
        migrations.AddField(
            model_name='cruises',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='Cruise', to='cruises.Tag'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='cruises.tickets'),
        ),
    ]
