# Generated by Django 3.2.18 on 2023-03-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruises', '0002_auto_20230327_1208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ships',
            options={'verbose_name_plural': 'Ships'},
        ),
        migrations.AddField(
            model_name='destination',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
