# Generated by Django 3.2.18 on 2023-04-04 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cruises', '0003_auto_20230328_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='cruise_name_str',
            field=models.CharField(editable=False, max_length=120, null=True, verbose_name='Cruise Name'),
        ),
        migrations.AddField(
            model_name='suitecategories',
            name='category_deckplan',
            field=models.ImageField(null=True, upload_to='', verbose_name='Category Deckplan'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='booked_by',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_ticket', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking', to='cruises.tickets'),
        ),
        migrations.AlterField(
            model_name='fares',
            name='cruise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fares', to='cruises.cruises'),
        ),
    ]
