# Generated by Django 3.2.18 on 2023-04-05 17:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruises', '0004_auto_20230404_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fares',
            name='offer_price',
        ),
        migrations.RemoveField(
            model_name='fares',
            name='special_offer',
        ),
        migrations.AlterField(
            model_name='ships',
            name='total_suites',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(100)], verbose_name='Total number of suites on ship'),
        ),
    ]
