# Generated by Django 3.2.18 on 2023-04-22 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cruises', '0007_alter_cruises_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookings',
            options={'verbose_name_plural': 'Bookings'},
        ),
        migrations.AlterModelOptions(
            name='cruises',
            options={'verbose_name_plural': 'Cruises'},
        ),
        migrations.AlterModelOptions(
            name='fares',
            options={'verbose_name_plural': 'Fares'},
        ),
        migrations.AlterModelOptions(
            name='guests',
            options={'verbose_name_plural': 'Guests'},
        ),
        migrations.AlterModelOptions(
            name='movements',
            options={'verbose_name_plural': 'Movements'},
        ),
        migrations.AlterModelOptions(
            name='suitecategories',
            options={'verbose_name_plural': 'Suite Categories'},
        ),
        migrations.AlterModelOptions(
            name='suites',
            options={'verbose_name_plural': 'Suites'},
        ),
        migrations.AlterModelOptions(
            name='tickets',
            options={'verbose_name_plural': 'Tickets'},
        ),
        migrations.RemoveField(
            model_name='guests',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='guests',
            name='dietary_requirements',
        ),
        migrations.RemoveField(
            model_name='guests',
            name='email',
        ),
        migrations.RemoveField(
            model_name='guests',
            name='state_county',
        ),
        migrations.RemoveField(
            model_name='guests',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='guests',
            name='title',
        ),
    ]
