# Generated by Django 3.2.18 on 2023-04-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruises', '0008_auto_20230422_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guests',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='guests',
            name='country_residence',
        ),
        migrations.RemoveField(
            model_name='guests',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='guests',
            name='town_city',
        ),
        migrations.RemoveField(
            model_name='guests',
            name='zip_postcode',
        ),
        migrations.AddField(
            model_name='guests',
            name='phone_number',
            field=models.CharField(default=0, max_length=16, verbose_name='Phone Number'),
            preserve_default=False,
        ),
    ]
