# Generated by Django 3.2.18 on 2023-04-22 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruises', '0009_auto_20230422_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='guests',
            name='email',
            field=models.EmailField(default='', max_length=120),
        ),
    ]
