# Generated by Django 3.2.18 on 2023-04-25 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cruises', '0010_guests_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
    ]
