# Generated by Django 3.2.18 on 2023-04-25 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cruises', '0011_remove_tag_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='slug',
        ),
    ]
