# Generated by Django 3.2.18 on 2023-04-26 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruises', '0012_remove_destination_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='guests',
            field=models.CharField(default='', max_length=2000, verbose_name='Guests JSON'),
        ),
        migrations.DeleteModel(
            name='Guests',
        ),
    ]
