# Generated by Django 3.2.18 on 2023-04-27 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cruises', '0013_auto_20230426_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='cruises.tickets'),
        ),
    ]
